version: 2.1

orbs:
  sam: circleci/aws-sam-serverless@6.1.0

jobs:
  build:
    executor: sam/default
    steps:
      - checkout
      - sam/install
      - run:
          command: yarn
      - run:
          command: yarn build

  # test:
  #   executor: nodejs
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys:
  #           - tf-v1-{{ checksum "yarn.lock" }}
  #     - run:
  #         command: yarn test

  deploy:
    executor: sam/default
    steps:
      - checkout
      - sam/install
      - run:
          command: yarn
      - run:
          command: yarn deploy

workflows:
  lambda:
    jobs:
      - build:
          context: global
      # - test:
      #     context: global
      #     requires: [build]
      - deploy:
          context: global
          requires: [build]
          filters:
            branches:
              only: master
