version: 2.1

orbs:
  sam: circleci/aws-sam-serverless@6.1.0

jobs:
  build_deploy:
    executor: sam/default
    steps:
      - checkout
      - sam/install
      - run:
          command: yarn
      - run:
          command: yarn build
      - run:
          command: yarn deploy

  # test:
  #   executor: nodejs
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys:
  #           - tf-v1-{{ checksum "yarn.lock" }}
  #     - run:
  #         command: yarn test

  # deploy:
  #   executor: sam/default
  #   steps:
  #     - checkout
  #     - sam/install
  #     - run:
  #         command: yarn
  #     - run:
  #         command: yarn deploy

workflows:
  aws-sam:
    jobs:
      - build_deploy:
          context: dev
      # - test:
      #     context: global
      #     requires: [build]
      # - deploy:
      #     context: dev
      #     requires: [build]
      #     filters:
      #       branches:
      #         only: master
