version: 2.1

orbs:
  sam: circleci/aws-sam-serverless@6.1.0

jobs:
  build_deploy:
    executor: sam/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - sam-v1-{{ checksum "yarn.lock" }}
      - sam/install
      - run:
          command: yarn
      - run:
          command: yarn build
      - run:
          command: yarn deploy
      # - persist_to_workspace:
      #     root: .
      #     paths:
      #       - node_modules
      - save_cache:
          key: sam-v1-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  # test:
  #   executor: nodejs
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys:
  #           - tf-v1-{{ checksum "yarn.lock" }}
  #     - run:
  #         command: yarn test

  # deploy:
  #   executor: sam/default
  #   steps:
  #     - checkout
  #     - sam/install
  #     - run:
  #         command: yarn
  #     - run:
  #         command: yarn deploy

workflows:
  aws-sam:
    jobs:
      - build_deploy:
          context: global
      # - test:
      #     context: global
      #     requires: [build]
      # - deploy:
      #     context: dev
      #     requires: [build]
      #     filters:
      #       branches:
      #         only: master
